#!/bin/bash

function replace_sxhkd () {
    local hook="$1"
    local config="$(echo ~)/.config/sxhkd/$2"

    polybar-msg action "#sxhkd.hook.$hook" &
    pkill -o -x sxhkd
    wait
    sxhkd -c $config &
}

function main () {
    local hook="${1:-0}"
    local config="${2:-"sxhkdrc"}"

    replace_sxhkd "$hook" "$config"
}

main $1 $2
