#!/bin/bash
include=(kitty bspwm)

function required_check() {
    local package="$1"

    if pacman -Qs "$package" > /dev/null ; then
        echo "$package is installed."
        return 0
    else
        echo "$package is not installed, this script won't work."
        exit
    fi
}

function vscode() {
    local packages=(esbenp.prettier-vscode catppuccin.catppuccin-vsc pkief.material-icon-theme twxs.cmake)
    if pacman -Qs "vscodium" > /dev/null ; then
        for element in "${packages[@]}"; do
            vscodium --install-extension "$element"
        done
    else
        echo "vscodium is not installed."
    fi
}

function create_directory_skeleton() {
   local target="$1"
   local skel="skel"
   cp -R "$skel/." "$target"
}

function install_dotfiles() {
    local target="$1"
    for element in "${include[@]}"; do
        echo "installing $element configs!"
        stow "$element" --target "$target"
    done
}

function remove_dotfiles() {
    local target="$1"
    for element in "${include[@]}"; do
        echo "removing $element configs!"
        stow -D "$element" --target "$target"
    done

    # Had an issue where .config was being deleted
    # run this again to recreate the desired directory
    # skeleton
    create_directory_skeleton "$target"
}

function main() {
    echo "Installing Momijie's dotfiles!"
    local target="$HOME/test"
}

target="$HOME/test"

required_check "stow"



create_directory_skeleton "$target"

install_dotfiles "$target"

remove_dotfiles "$target"
