#! /bin/sh

function restart_sxhkd () {
    local sxhkd_config="$HOME/.config/sxhkd"
    if command -v sxhkd & > /dev/null; then
        local adds="$(find $sxhkd_config -type l -xtype f -not -name 'sxhkdrc' -not -name 'picture_mode.extra' -not -name 'system_mode.extra' | paste -sd " ")"
        grep -x sxhkd > /dev/null || sxhkd -c  "$sxhkd_config/sxhkdrc" $adds &
    fi
}

function monitor () {
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
}

function launch () {
    pgrep -x autokey-gtk > /dev/null || autokey-gtk &
    ~/.fehbg &
    polybar mainbar-bspwm -c  ~/.config/polybar/config &
    picom &
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    /usr/bin/emacs --daemon &
    pgrep redshift > /dev/null || redshift &
    xmodmap -e "pointer = 1 25 3 4 5 6 7 8 9"
    keynav &
}

function config () {
    bspc config border_width         2
    bspc config window_gap           0
    bspc config split_ratio          0.52
    bspc config borderless_monocle   true
    bspc config gapless_monocle      true
    bspc config focus_follows_pointer true
}

function rules () {
    bspc rule -a librewolf-default desktop='^2' focus=on follow=on
    bspc rule -a kitty state=floating center=true rectangle=960x540+0+0
    bspc rule -a Thunar state=floating center=true rectangle=960x540+0+0
    bspc rule -a Nitrogen state=floating center=true rectangle=960x540+0+0
    bspc rule -a Nsxiv state=floating center=true focus=on follow=on desktop='^1'
    bspc rule -a Code desktop='^3' focus=on follow=on
    bspc rule -a Virt-viewer desktop='^4' focus=on follow=on
    bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on
    bspc rule -a Emacs desktop='^1' focus=on follow=on state=fullscreen
}

function main () {
    restart_sxhkd
    xrdb -merge "$HOME/.Xresources"
    monitor
    launch
    config
    rules
}

main
